
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const page = () => {
  return (
    <div className='HomePage' >
      <h1>Home Page</h1>
    </div>
  )
}

export default page